# Generated by Django 4.0.2 on 2024-10-13 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_options_alter_review_options_and_more'),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitingtime',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiting_time', to='doctors.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='visitingtime',
            name='is_booked',
            field=models.BooleanField(blank=True, default=False, verbose_name='Booked'),
        ),
        migrations.AlterField(
            model_name='visitingtime',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time end'),
        ),
    ]
