# Generated by Django 4.0.2 on 2023-05-11 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitingtime',
            name='max_time',
        ),
        migrations.AddField(
            model_name='visitingtime',
            name='time_end',
            field=models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(240), django.core.validators.MinValueValidator(15)], verbose_name='Конечное время'),
        ),
    ]
