# Generated by Django 4.0.2 on 2023-05-11 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_remove_visitingtime_max_time_visitingtime_time_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitingtime',
            name='max_time',
            field=models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(240), django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='visitingtime',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конечное время'),
        ),
    ]
