# Generated by Django 4.0.2 on 2023-04-28 21:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('calendars', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedCall',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a7e2d939-03d0-4556-9303-7db7fb2fa708'), primary_key=True, serialize=False)),
                ('call_start', models.DateTimeField()),
                ('call_end', models.DateTimeField(blank=True, default=None)),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешный')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_ordered_calls', to='accounts.client', verbose_name='Клиент')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_ordered_calls', to='doctors.doctor', verbose_name='Доктор')),
                ('visiting_time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oredered_call', to='calendars.visitingtime', verbose_name='Время визита')),
            ],
        ),
    ]
