# Generated by Django 4.0.2 on 2023-05-10 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('418ad3a5-8b33-408e-905b-f09c458c69af'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('29e883be-0d0e-4c22-b110-7ad52e59854d'), primary_key=True, serialize=False),
        ),
    ]
