# Generated by Django 4.0.2 on 2023-04-28 21:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedcall',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ba428746-6d48-491a-8341-a80e5acc7fcd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='visiting_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_call', to='calendars.visitingtime', verbose_name='Время визита'),
        ),
    ]
