# Generated by Django 4.0.2 on 2023-05-10 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_adminchat_id_alter_premiumchat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminchatmessage',
            name='read',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='premiumchatmessage',
            name='read',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('91b36abb-a09d-4d6c-ad60-32e8ad8530be'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e734fa8-2281-4f9f-981c-c1e5534d43b4'), primary_key=True, serialize=False),
        ),
    ]
