# Generated by Django 4.0.2 on 2023-05-15 22:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_adminchat_id_alter_premiumchat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminchatmessage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='premiumchatmessage',
            name='date',
        ),
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3ceff436-3dce-4d4c-ab58-9f20ee3358d6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('53702076-5866-4c1c-b2ca-7f71431dac30'), primary_key=True, serialize=False),
        ),
    ]
