# Generated by Django 4.0.2 on 2023-05-14 13:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_adminchat_id_alter_premiumchat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('10aafbdb-b723-493c-826c-df99f9a95234'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5e808e5c-aab1-43f9-97fe-7f7fb4f4b2e2'), primary_key=True, serialize=False),
        ),
    ]
