# Generated by Django 4.0.2 on 2023-05-02 14:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_adminchat_adminchatmessage_premiumchatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1c006d0-dffb-4a8b-a4c9-27e8585fe1cc'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='id',
            field=models.UUIDField(default=uuid.UUID('34f1cc4b-33cd-494f-9329-a692099f4505'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5d68b4c7-e822-48c3-91cc-b44a3219ca9f'), primary_key=True, serialize=False),
        ),
    ]
