# Generated by Django 4.0.2 on 2024-10-12 15:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_adminchat_id_alter_premiumchat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b2386675-83b2-4457-bd61-6002974ccb78'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('23352880-0afe-4b21-91e8-4414c789dcca'), primary_key=True, serialize=False),
        ),
    ]
