# Generated by Django 4.0.2 on 2023-05-14 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_adminchat_id_alter_premiumchat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1fea4be2-5534-45e4-a8be-759e5d072c0a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a37be258-efa0-4bf1-9c71-4df37e19e11a'), primary_key=True, serialize=False),
        ),
    ]
