# Generated by Django 4.0.2 on 2023-05-10 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_adminchatmessage_read_premiumchatmessage_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a05f5d2-934f-49b8-9df0-c61cf717e3d7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8dc2b7d-593f-47cc-99e0-bbaa2569ed78'), primary_key=True, serialize=False),
        ),
    ]
