# Generated by Django 4.0.2 on 2024-10-13 12:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0002_alter_visitingtime_doctor_and_more'),
        ('chat', '0003_alter_adminchat_id_alter_premiumchat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('160286e1-6c6c-4b78-9a32-fba38dbc3538'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='is_ended',
            field=models.BooleanField(default=False, verbose_name='Ended'),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='ordered_time',
            field=models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(240)], verbose_name='Call time'),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='visiting_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_call', to='calendars.visitingtime', verbose_name='Visit time'),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('296c7cf1-48f9-425f-b1f9-a5f3c1e0569e'), primary_key=True, serialize=False),
        ),
    ]
