# Generated by Django 4.0.2 on 2024-10-13 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_adminchat_id_alter_orderedcall_is_ended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7edeafaa-79dd-4869-abb9-ac2e6dd648d5'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cd5067d2-18f6-422e-9146-56f59b0ec719'), primary_key=True, serialize=False),
        ),
    ]
