# Generated by Django 4.0.2 on 2023-05-10 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_adminchat_id_alter_premiumchat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fb03b012-a050-4d53-b215-54a8a259b5db'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cd502614-0ce6-4497-8bc9-a122d47c924c'), primary_key=True, serialize=False),
        ),
    ]
