# Generated by Django 4.0.2 on 2023-05-06 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_orderedcall_client_remove_orderedcall_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('960fbccf-cba6-434b-a3ee-5aa55bbc93f3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1e687983-2a14-4ff3-bd33-fdd5eaf2a9e2'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c66a941b-9541-496b-8024-3502e4db6433'), primary_key=True, serialize=False),
        ),
    ]
