# Generated by Django 4.0.2 on 2023-05-10 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_adminchat_id_alter_premiumchat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63b48511-56b5-4ac7-94ea-7afcb015eb7c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5a1c4927-d4fb-4d2d-8d9e-9f2dd73d643e'), primary_key=True, serialize=False),
        ),
    ]
