# Generated by Django 4.0.2 on 2024-10-13 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_adminchat_id_alter_premiumchat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e16d976d-ccfa-4835-8764-b1859926b51a'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f05a4895-476d-4ed7-85ce-2fd01477fb2c'), primary_key=True, serialize=False),
        ),
    ]
