# Generated by Django 4.0.2 on 2023-05-06 14:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_adminchat_id_alter_orderedcall_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('76b421ed-ca2e-4ab3-90cf-b1a8d2b0e726'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='call_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c191d7eb-f28f-438a-9b66-bac9c59a6677'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('701e9420-fbe2-46b8-8407-19da97c9a357'), primary_key=True, serialize=False),
        ),
    ]
