# Generated by Django 4.0.2 on 2023-05-08 20:02

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_adminchat_id_alter_orderedcall_call_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('85be2dad-f3cb-49f3-b236-1ba598b886b3'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5dff96fd-cf25-456d-91f7-f0f80cbad9b6'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='ordered_time',
            field=models.IntegerField(default=60, validators=[django.core.validators.MaxValueValidator(240)], verbose_name='Время звонка'),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4cc729a8-6ab5-4f54-95fb-a6758a4c41f4'), primary_key=True, serialize=False),
        ),
    ]
