# Generated by Django 4.0.2 on 2023-05-08 22:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_adminchat_id_alter_orderedcall_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('38151ef6-32e5-4633-974a-d191f215113e'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='id',
            field=models.UUIDField(default=uuid.UUID('553e0fd3-119d-48c4-9190-aa5a18949349'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a0bd53aa-f275-4b91-a28f-7fb07b16116f'), primary_key=True, serialize=False),
        ),
    ]
