# Generated by Django 4.0.2 on 2023-05-11 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_adminchat_id_alter_premiumchat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b0689ce7-f998-46c7-b682-5853016aa79c'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('50537181-f4a4-4eef-965b-369116d59fda'), primary_key=True, serialize=False),
        ),
    ]
