# Generated by Django 4.0.2 on 2023-05-11 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_adminchat_id_alter_premiumchat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ba8f878e-8f72-4f0a-88e5-2c93da708f93'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8bcbc80d-7be2-42ee-aaca-af5e896bf282'), primary_key=True, serialize=False),
        ),
    ]
