# Generated by Django 4.0.2 on 2023-05-08 22:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_adminchat_id_alter_orderedcall_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ba9b2cb0-acd5-4cc9-ad9e-4b65242c0f3d'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='id',
            field=models.UUIDField(default=uuid.UUID('323560a2-5ea7-4b27-8d2b-3476f867a464'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4da4ef3-4df8-4ed2-92a7-52c9d75409a4'), primary_key=True, serialize=False),
        ),
    ]
