# Generated by Django 4.0.2 on 2023-05-11 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_adminchat_id_alter_premiumchat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedcall',
            name='is_ended',
            field=models.BooleanField(default=False, verbose_name='Завершенный'),
        ),
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('59c00d20-85e4-4cd3-a679-b75550dc6896'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b99b2d9e-fdd7-423c-9cbf-0cf89f302d87'), primary_key=True, serialize=False),
        ),
    ]
