# Generated by Django 4.0.2 on 2023-05-11 21:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_visitingtime_max_time_alter_visitingtime_time_end'),
        ('chat', '0012_alter_adminchat_id_alter_orderedcall_visiting_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c1138e0b-7654-43aa-b4c6-eb639230ccf7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='visiting_time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_call', to='calendars.visitingtime', verbose_name='Время визита'),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a46ca082-c0d9-4280-9da9-83ff0db145ae'), primary_key=True, serialize=False),
        ),
    ]
