# Generated by Django 4.0.2 on 2023-05-11 21:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_visitingtime_max_time_alter_visitingtime_time_end'),
        ('chat', '0013_alter_adminchat_id_alter_orderedcall_visiting_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d1005764-3174-4b49-9a32-d5f6696aa6b8'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderedcall',
            name='visiting_time',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_call', to='calendars.visitingtime', verbose_name='Время визита'),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0042e694-32f2-470a-b1ec-162ff624dbef'), primary_key=True, serialize=False),
        ),
    ]
