# Generated by Django 4.0.2 on 2023-05-11 21:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_alter_adminchat_id_alter_orderedcall_visiting_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedcall',
            name='is_ended',
            field=models.BooleanField(default=False, verbose_name='Завершеный'),
        ),
        migrations.AlterField(
            model_name='adminchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1bc563d6-7ec1-4f2d-afb4-2a543c3386fd'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premiumchat',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d501b836-b965-4368-a9bc-6f5a3c5fda7c'), primary_key=True, serialize=False),
        ),
    ]
