# Generated by Django 4.0.2 on 2023-05-10 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_adminchat_id_alter_premiumchat_id'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='ordered_call',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_call_complaint', to='chat.orderedcall', verbose_name='Звонок'),
        ),
    ]
