# Generated by Django 4.0.2 on 2023-04-25 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationphoto',
            name='certification_confirmation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moderation.certificationconfirmation', verbose_name='Подтверждение конфигураций'),
        ),
    ]
