# Generated by Django 4.0.2 on 2023-05-06 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationconfirmation',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='doctors.doctor', verbose_name='Доктор'),
        ),
    ]
