# Generated by Django 4.0.2 on 2024-10-13 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0004_alter_qualification_name'),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificationconfirmation',
            options={'verbose_name': 'Certification confirmation', 'verbose_name_plural': 'Certification confirmations'},
        ),
        migrations.AlterModelOptions(
            name='certificationphoto',
            options={'verbose_name': 'Certification Photo', 'verbose_name_plural': 'Certification Photos'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterField(
            model_name='certificationconfirmation',
            name='qualifications',
            field=models.ManyToManyField(to='doctors.Qualification', verbose_name='Request for certifications'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='accused',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accused_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Accused'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='cause',
            field=models.CharField(max_length=150, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiator_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Initiator'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='standardcomplaint',
            name='accused',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accused_standard_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Accused'),
        ),
        migrations.AlterField(
            model_name='standardcomplaint',
            name='cause',
            field=models.CharField(max_length=150, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='standardcomplaint',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiator_standard_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Initiator'),
        ),
    ]
