# Generated by Django 4.0.2 on 2023-04-25 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('moderation', '0002_alter_certificationphoto_certification_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationconfirmation',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='doctors.doctor', verbose_name='Доктор'),
        ),
    ]
