# Generated by Django 4.0.2 on 2023-05-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_alter_complaint_ordered_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='solved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
