# Generated by Django 4.0.2 on 2023-05-08 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0002_alter_certificationconfirmation_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=150, verbose_name='Причина')),
                ('accused', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accused_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Обвиняемый')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initiator_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Жалоба на доктора',
                'verbose_name_plural': 'Жалобы на докторов',
            },
        ),
        migrations.RemoveField(
            model_name='doctorcomplaint',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='ClientComplaint',
        ),
        migrations.DeleteModel(
            name='DoctorComplaint',
        ),
    ]
