# Generated by Django 4.0.2 on 2023-05-14 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0002_remove_complaint_ordered_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=150, verbose_name='Причина')),
                ('accused', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accused_standard_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Обвиняемый')),
                ('initiator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiator_standard_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
        ),
    ]
