# Generated by Django 4.0.2 on 2023-04-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('doctors', '0002_remove_doctor_qualification_doctor_qualifications_and_more'),
        ('moderation', '0003_alter_certificationconfirmation_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationconfirmation',
            name='qualifications',
            field=models.ManyToManyField(to='doctors.Qualification', verbose_name='Квалификации'),
        ),
        migrations.AlterField(
            model_name='clientcomplaint',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='doctorcomplaint',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='Доктор'),
        ),
    ]
