# Generated by Django 4.0.2 on 2023-05-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_adminchat_id_alter_orderedcall_id_and_more'),
        ('moderation', '0003_complaint_remove_doctorcomplaint_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'Жалоба', 'verbose_name_plural': 'Жалобы'},
        ),
        migrations.AddField(
            model_name='complaint',
            name='ordered_call',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.orderedcall', verbose_name='Звонок'),
        ),
    ]
