# Generated by Django 4.0.2 on 2023-04-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_rating'),
        ('moderation', '0004_certificationconfirmation_qualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificationconfirmation',
            name='qualifications',
            field=models.ManyToManyField(to='doctors.Qualification', verbose_name='Запрос на получение квалификации'),
        ),
    ]
