# Generated by Django 4.0.2 on 2023-04-27 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='qualification',
        ),
        migrations.AddField(
            model_name='doctor',
            name='qualifications',
            field=models.ManyToManyField(related_name='doctors', to='doctors.Qualification', verbose_name='Квалификации'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='is_confirmed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Подтвержден'),
        ),
        migrations.AlterField(
            model_name='review',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='doctors.doctor', verbose_name='Доктор'),
        ),
    ]
