# Generated by Django 4.0.2 on 2023-05-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='service_cost',
            field=models.PositiveIntegerField(verbose_name='Стоимость услуг'),
        ),
    ]
