# Generated by Django 4.0.2 on 2023-04-27 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_remove_doctor_qualification_doctor_qualifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
