# Generated by Django 4.0.2 on 2024-10-13 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualification',
            options={'verbose_name': 'Qualification', 'verbose_name_plural': 'Qualifications'},
        ),
    ]
