# Generated by Django 4.0.2 on 2024-10-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_qualification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
